### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add linux aarch64 wheel build support.

Related to https://github.com/equinor/segyio/issues/518 @jokva Could you please review this PR?

### CODE REVIEW

**Comment by odidev** [comment]
@jokva, May I know when the release for Linux AArch64 wheel is scheduled? Thanks.

**Comment by jokva** [comment]
The short answer is "I don't know" - I don't maintain segyio anymore as I am no longer in Equinor. I don't know who maintains it now, I'm afraid.

**Comment by odidev** [comment]
ok, Thanks @jokva 

Equinor Team May I know when the release for the Linux AArch64 wheel is scheduled? Thanks.

**Comment by jsrz** [comment]
If we can't get an ETA, it might be good to at least understand when their next version is going to be released. Then you can either look at the release notes or try it out.

**Comment by ErlendHaa** [comment]
I've published a new version, 1.9.9, which includes prebuilt wheels for linux aarch64.

**Pull request merged**
