### PR TITLE
Associate a size with each field

### LINKED ISSUE #407: Can not open SEGY with long traces
I tried to open a file with traces of 60000 samples each and I got the following error: `RuntimeError: trace count inconsistent with file size, trace lengths possibly of non-uniform`

After some debug I found out that it's because the "Number of expected samples per trace" is read as a signed 16 bit value. Is there any reason for that ?

I understand that the SEGY standard does not explicitly mention that this field is unsigned but a negative number of sample per trace does not really make sense

### PR DESCRIPTION
**Pull request by kurddt**
This allows to have 16bit unsigned field.

Resolves #407

### CODE REVIEW

**Comment by jokva** [comment]
Hi,

While I really appreciate the effort, you're still covering up _obvious_ standards violations. This kind of broken data _must not be covered up_ deep in the stack, it's an end-user decision to make if it should be interpreted as unsigned.

I'm sorry, but I won't merge this. If supporting >32k samples per trace is really important to you, it can be handled in the Python bit. Covering it up by silently reinterpreting broken data is not going to fly.

If you don't mind me asking, what kind survey is this with 60k samples?

**Comment by kurddt** [comment]
I understand you point. I will see what I can so on the python side

The data come from continuous recording, a trace being one minute of data

**Comment by jokva** [comment]
> I understand you point. I will see what I can so on the python side

It might be _slightly_ involved to get all the details right, but I'm available if you need help, or if you want to hand it off. Regardless, I'm very thankful for this contribution.

> The data come from continuous recording, a trace being one minute of data

Interesting. Good thing you cut it after one minute, because you only have ~5.5k more samples to spare. :----------)

**Comment by kurddt** [comment]
I will close this PR then since #408 seems to be a better starting point.

> It might be slightly involved to get all the details right, but I'm available if you need help, or if you want to hand it off. Regardless, I'm very thankful for this contribution.

You are welcome. I'm not sure when or how much time I will take me to do that, so if you want to implement it please go ahead.

**Pull request closed without merging**
