### PR TITLE
catch2: v2.2.3 -> v2.13.9

### PR DESCRIPTION
**Pull request by AtilaSaraiva**
Hello folks from Equinor,

I've been packaging segyio for the [Nix package manager](nixos.org) but I stumbled upon the catch2 error described [here](https://github.com/catchorg/Catch2/issues/2178). It has been solved in more recent versions of catch2, so I'm making this PR to bump the version in order to fix it.

Cheers!

### CODE REVIEW

**Comment by tasansal** [comment]
+1 for this. The issue I encountered is on OS X ARM64 (aarch64). `segyio` wasn't compiling due to the lack of aarch64 assembly instructions for the older version of `catch2`.

I can confirm that with this change, I could compile `segyio` from the source on an Apple M1 device.

**Comment by ErlendHaa** [comment]
Hi! 

Thank you for the contribution, and sorry for the late reply! If you could rebase on master to allow CI to run once more, then I will happy approve and merge this :)

**Comment by AtilaSaraiva** [comment]
Oh no problem, just gimme some minutes

**Comment by AtilaSaraiva** [comment]
Done!

**Review by ErlendHaa — APPROVED** [review]
LGTM! Thanks for the contribution

**Comment by AtilaSaraiva** [comment]
Thanks!

**Pull request merged**
